/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'IMaterialSymbols:editCalendarSharp': typeof import('~icons/material-symbols/edit-calendar-sharp')['default']
    'IMaterialSymbols:folderOpenRounded': typeof import('~icons/material-symbols/folder-open-rounded')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
